# Generated by Django 3.2.11 on 2022-01-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='年齢'),
        ),
    ]
