# Generated by Django 3.2.11 on 2022-01-22 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20220123_0014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workdetail',
            options={'verbose_name_plural': '作品の詳細文'},
        ),
    ]
