# Generated by Django 3.2.11 on 2022-01-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20220122_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='detail',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='詳細'),
        ),
    ]
